# Generated by Django 4.1.2 on 2022-12-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_color_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
