# Generated by Django 4.1.2 on 2022-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_colorvariant_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(blank=True, default='#000000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='color_name',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(default='S', max_length=100),
        ),
    ]
