# Generated by Django 4.1.2 on 2022-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_colorvariant_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_variant',
            field=models.ManyToManyField(blank=True, default='#000000', to='store.colorvariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size_variant',
            field=models.ManyToManyField(blank=True, default='S', to='store.sizevariant'),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(max_length=100),
        ),
    ]
