# Generated by Django 4.2.2 on 2023-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_useraddressbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='active',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
